# -*- coding: utf-8 -*-
#
# XML definitions for the DS software
# 
# Hervé Déjean, 2016
#
# Copyright XRCE, 2016
# READ project


## pdftoxml tag ames
sFontName = "font-name"
sFontSize =  "font-size"
sFontColor = "font-color"
sBold = "bold"
sItalic = "italic"

sRotation = "rotation"


sIdAttr = "id"

#For the Header/Footer detector
sHF_HeaderAttr = "header"
sHF_FooterAttr = "footer"
sHF_SideAttr = "sider"

#Footnotes
sNoteAttr = "Note"
sNoteAnchorAttr= "NoteAnchor"


#For the xy_cutter segmenter and reorderer
sCOL_Elt          = "COLUMN"       #id like "cPP_NN"
sPARAG_Elt        = "PARAGRAPH"    #id like "pPP_NN"
sLINE_Elt         = "LINE"         #id like "lPP_NN"

sTOKEN = "TOKEN"
sTEXT = "TEXT"
sPAGE = "PAGE"
sX = "x"
sY = "y"
sHeight = "height"
sWidth = "width"
sPageNumber = "number"
sXY_IMAGE_Elt = "IMAGE"
sXY_GROUP_Elt = "GROUP"
sGALLEY       = "GALLEY"
sGraphicalElt ="GRAPHELT"
sBaseline = "BASELINE"

sBLOCK = "BLOCK"
sTABLE = "TABLE"
sROW   = "ROW"
sCELL  = "CELL"
sFRAME = "FRAME"

sUnderline = "underline"
## for Alignment
sAlign_ELT = "text-align"
sAlign_Justified = "justified"
sAlign_Center = "center"
sAlign_Left = "left"
sAlign_Right = "right"
# alignment wrt parent
sAlign_Parent = "position"

sIndent = "Indent"
sHanging = "Hanging"
sTAB = "TAB"

sCaption = "caption"

# XML tag used in XML file configuration for each tool
sCONFIGURATION = "CONFIGURATION"
sTOOL = "TOOL"
sNAME = "NAME"
sVERSION = "VERSION"
sDESCRIPTION = "DESCRIPTION"
sPARAM = "PARAM"
sCMD = "CMD"
sOPTIONSHORT = "OPTIONSHORT"
sOPTIONLONG = "OPTIONLONG"
sARG = "ARG"
sTYPE = "TYPE"
sDEFAULTVALUE = "DEFAULTVALUE"
sATTR_NAME = "name"
sATTR_FORM = "form"

sXML_VERSION = "1.0"
sENCODING_UTF = "UTF-8"

sDOCUMENT = "DOCUMENT"
sMETADATA = "METADATA"
sPROCESS = "PROCESS"
sVERSION = "VERSION"
sCOMMENT = "COMMENT"
sCREATIONDATE = "CREATIONDATE"
sATTR_CMD = "cmd"
sATTR_CMD_ARG = "cmd_arg"
sATTR_VALUE = "value"

#XML tags and attributes used in XML outline file generated by pdftoxml
sTOCITEMS = "TOCITEMS" 
sTOCITEMLIST = "TOCITEMLIST"
sITEM = "ITEM"
sSTRING = "STRING"
sLINK = "LINK"

sATTR_NBPAGES = "nbPages"
sATTR_LEVEL = "level"
sATTR_IDITEMPARENT = "idItemParent"
sATTR_PAGE = "page"
sATTR_TOP = "top"
sATTR_BOTTOM = "bottom"
sATTR_LEFT = "left"
sATTR_RIGHT = "right"


